apiVersion: v1
kind: Pod
metadata:
  name: tools
  labels:
    app: tools
spec:
  nodeSelector:
    kubernetes.io/hostname: sgh607tzfs
  containers:

  - name: tools
    image: ichte/coretools
    resources: {}
    command: ["/bin/bash"]
    args: ["-c", "while true; do echo 'busybox running'; sleep 10;done"]
