apiVersion: v1
kind: Pod
metadata:
  name: tools
  labels:
    name: tools
spec:
  containers:
  - name: tools
    image: ichte/coretools
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    command: ["/bin/bash"]
    args: ["-kc", "while true; do echo busy running; sleep; done"]