apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: deployapp
  namespace: default
  resourceVersion: "268341"
  uid: 80921c9e-883c-4450-9f33-0f761b1f31a9
spec:
  maxReplicas: 10
  minReplicas: 5
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deployapp
  targetCPUUtilizationPercentage: 80
status:
  currentReplicas: 5
  desiredReplicas: 5
